Feature/ccle 9588 invite note on ical
jrchamp/moodle-mod_zoom pull request #167
Opened 2020-11-23 17:46 UTC by jackvanb

The Zoom meeting invitation text is added to the iCal description export. This includes the Zoom meeting link and the call-in information.

<img width="277" alt="Screen Shot 2020-11-20 at 8 26 20 PM" src="https://user-images.githubusercontent.com/17104896/99995295-0301c700-2d6f-11eb-9920-e7c44dc1549b.png">

2020-11-23 19:07 UTC, rlorenzo requested changes
@jackvanb Please see my comments here

2020-11-23 19:07 UTC, rlorenzo commented on classes/webservice.php
> +            throw $error;
@jackvanb the Zoom API has not been rock stable and occasional times out or is unavailable. Rather than throwing an exception, can you make it just return null but have some debugging that outputs the error?

```
debugging($error->getMessage());
return $response;
```

This is not such an important web service call that we want to interrupt a user's flow.

2020-11-23 19:07 UTC, rlorenzo commented on exportical.php
> +$descriptiontext .= PHP_EOL . $meetinginvite;
@jackvanb According to https://stackoverflow.com/questions/666929/encoding-newlines-in-ical-files

A newline in iCal is \n or rather \\n. Also can you add double new line, because from the screenshot it looks like it can be improved by having an extra new line after the CCLE URL.

2020-11-23 20:54 UTC, jackvanb commented on classes/webservice.php
> +            throw $error;
Fixed.

2020-11-23 20:55 UTC, jackvanb commented on exportical.php
> +$descriptiontext .= PHP_EOL . $meetinginvite;
Added double new line and updated screenshot.

2020-11-23 22:15 UTC, rlorenzo commented on classes/webservice.php
> +            debugging($error->getMessage());
@jackvanb  Why are you changing this function?

2020-11-23 22:35 UTC, jackvanb commented on classes/webservice.php
> +            debugging($error->getMessage());
Oops, modified the wrong function. Fixed.

2020-11-23 23:25 UTC, rlorenzo approved these changes

2020-11-23 23:27 UTC, rlorenzo commented
@jackvanb Looks good now. Please put this on TEST. Follow these procedures:

1. Squash your commits for this branch into a single commit
2. In this repo merge your branch to the development branch. Push to Github
3. In the ucla/mood repo, check out the development branch, and commit your changes to mod/zoom. Push to Github.
4. TEST should now have your changes so we can test them. Document testing instructions in the description in JIRA, then I can assign it to one of our testers to verify.

2020-11-25 16:49 UTC, merged

2020-11-25 17:23 UTC, rlorenzo commented
@jackvanb  You said this was merged to development, but when I tested on test at https://test.ccle.ucla.edu/mod/zoom/view.php?id=68704&forceview=1

The iCal file is still didn't have the phone info